//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CRMFrontEnd.rc
//

#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128


#define IDD_ADD_CUSTOMER_CONTACT_VIEW	101
#define IDD_CONTACT_VIEW		102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_CRMFRONTEND			107
#define IDI_SMALL				108
#define IDC_CRMFRONTEND			109
#define IDD_MAIN_DIALOG			110
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif




#define IDC_CUSTOMER_NAME					1000
#define IDC_CUSTOMER_EMAIL					1001
#define IDC_CUSTOMER_PHONE					1002
#define IDC_CUSTOMER_NEXT_CONTACT_DATE		1003


#define IDC_CUSTOMER_UNIQUE_NAME			1004
#define IDC_CUSTOMER_NUM_CONTACTS			1005
#define IDC_CUSTOMER_LAST_CONTACT			1006
#define IDC_CUSTOMER_LAST_CONTACT_TYPE		1007
#define IDC_CUSTOMER_NOTES					1008
#define IDC_CUSTOMER_ADDED_DATE				1009
#define IDC_ADD_CONTACT						1010
#define IDC_SAVE_CUSTOMER					1011
#define IDC_UNIQUE_NAME						1012
#define IDM_LIST_VIEW_RESULTS				1013
#define IDC_CONTACT_NOTES					1014
#define IDC_IS_SUCCESSFUL_CONTACT			1015
#define IDC_CONTACT_TYPE					1016
#define IDC_DATE_CONTACTED					1017

#define IDC_EMAIL_LOOKUP_STATIC				1019
#define IDC_EMAIL_LOOKUP					1020
#define IDC_EMAIL_LOOKUP_OK					1021

#define IDC_NAME_LOOKUP_STATIC				1022
#define IDC_NAME_LOOKUP						1023
#define IDC_NAME_LOOKUP_OK					1024


#define IDC_PHONE_LOOKUP_STATIC				1025
#define IDC_PHONE_LOOKUP					1026
#define IDC_PHONE_LOOKUP_OK					1027

#define IDC_ADD_CUSTOMER					1028
#define IDC_CONVO_LIST_VIEW					1029
#define IDC_IS_ACTIVE_CUSTOMER				1030
#define IDC_TAG_LIST_VIEW					1031
#define IDC_ADD_NEW_TAGS_STATIC				1032
#define IDC_ADD_NEW_TAGS_OK					1033
#define IDC_ADD_NEW_TAGS_TEXT				1034

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif
